---
apiVersion: v1
kind: Secret
metadata:
  name: kctl-config
type: Opaque
stringData:
  plaintext.properties: |
    bootstrap.servers=default-kafka-plain-bootstrap.kafka.svc.cluster.local:9092
    security.protocol=PLAINTEXT

---

apiVersion: v1
kind: Pod
metadata:
  name: kctl
spec:
  containers:
  - name: kctl
    image: rafalskolasinski/kctl:latest
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - name: config-volume
      mountPath: /work/configs
      readOnly: true
  volumes:
  - name: config-volume
    secret:
      secretName: kctl-config
