name: Build and push kctl docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  kctl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest image
        working-directory: .
        run: make docker-build docker-push
